// Generates supabase/migrations/0008_seed_picks.sql from supabase/seed/*.csv.
// Run: npm run seed:generate
// The staging table keeps odds_scored (the sheet's as-entered, pre-doubled
// odds) so the validation gate can prove effective_odds reproduces the
// workbook on every one of the 1,287 rows.

import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const csv = readFileSync(join(root, 'supabase', 'seed', 'picks.csv'), 'utf8')

const lines = csv.trim().split(/\r?\n/)
const header = lines.shift()!
if (header !== 'date,player,acca_team,method,team,second_team,odds_scored,market_odds,doubled,win') {
  throw new Error(`Unexpected header: ${header}`)
}

const esc = (s: string) => `'${s.replace(/'/g, "''")}'`

const rows = lines.map((line, i) => {
  const parts = line.split(',')
  if (parts.length !== 10) throw new Error(`Row ${i + 2}: ${parts.length} fields`)
  const [date, player, accaTeam, method, team, secondTeam, oddsScored, marketOdds, doubled, win] = parts
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error(`Row ${i + 2}: bad date ${date}`)
  if (!['Win', 'BTTS', 'N/A'].includes(method)) throw new Error(`Row ${i + 2}: bad method ${method}`)
  if (!['0', '1'].includes(win)) throw new Error(`Row ${i + 2}: bad win ${win}`)
  if (!['0', '1'].includes(doubled)) throw new Error(`Row ${i + 2}: bad doubled ${doubled}`)
  if (Number.isNaN(Number(oddsScored)) || Number.isNaN(Number(marketOdds))) {
    throw new Error(`Row ${i + 2}: bad odds`)
  }
  const second = secondTeam === '' ? 'null' : esc(secondTeam)
  return `(${esc(date)},${esc(player)},${esc(accaTeam)},${esc(method)},${esc(team)},${second},${oddsScored},${marketOdds},${doubled},${win})`
})

console.log(`Parsed ${rows.length} picks`)
if (rows.length !== 1287) throw new Error(`Expected 1287 picks, got ${rows.length}`)

// Multi-row INSERTs in chunks to keep statements manageable.
const chunks: string[] = []
for (let i = 0; i < rows.length; i += 200) {
  chunks.push(
    `insert into seed_stage (gw_date, player, acca_team, method, team, second_team, odds_scored, market_odds, doubled, win) values\n` +
      rows.slice(i, i + 200).join(',\n') +
      ';',
  )
}

const sql = `-- GENERATED by scripts/generate-seed-sql.ts from supabase/seed/picks.csv.
-- Do not edit by hand; regenerate instead.

create table seed_stage (
  gw_date date not null,
  player text not null,
  acca_team text not null,
  method text not null,
  team text not null,
  second_team text,
  odds_scored numeric not null,
  market_odds numeric not null,
  doubled int not null,
  win int not null
);

${chunks.join('\n\n')}

-- Historic gameweeks from distinct pick dates, assigned to seasons by date
-- range. Windows are cosmetic for settled history.
insert into gameweeks (season_id, gw_date, window_opens, window_closes, status)
select s.id, d.gw_date,
       uk_ts(d.gw_date - 2, '18:00'), uk_ts(d.gw_date - 1, '20:00'),
       'settled'
from (select distinct gw_date from seed_stage) d
join seasons s on s.kind <> 'test' and d.gw_date between s.start_date and s.end_date;

-- Every seed date must have landed in exactly one season.
do $$
declare n int;
begin
  select count(*) into n
  from (select gw_date from seed_stage except select gw_date from gameweeks) t;
  if n > 0 then
    raise exception '% seed dates missing a gameweek (season ranges wrong?)', n;
  end if;
  select count(*) into n from gameweeks where status = 'settled';
  if n <> 108 then
    raise exception 'Expected 108 historic gameweeks, got %', n;
  end if;
end $$;

-- Back-set the final-GW flag on each finished season (no historic sweep fell
-- on a season final, so this changes no scores - the gate proves it).
update gameweeks g
set is_season_final = true
from (
  select g2.season_id, max(g2.gw_date) as gw_date
  from gameweeks g2
  join seasons s on s.id = g2.season_id
  where s.end_date < date '2026-08-10'
  group by g2.season_id
) m
where g.season_id = m.season_id and g.gw_date = m.gw_date;

-- Picks at MARKET odds; the scoring layer reproduces the doubled totals.
insert into picks (gameweek_id, player_id, method, team, second_team, odds, result, locked, submitted_at)
select g.id, p.id, st.method, st.team, st.second_team, st.market_odds,
       st.win::smallint, true, uk_ts(st.gw_date - 1, '19:00')
from seed_stage st
join gameweeks g on g.gw_date = st.gw_date
join players p on p.name = st.player;

-- Keep the stage as an admin-readable reference; the validation gate uses it.
alter table seed_stage enable row level security;
revoke all on seed_stage from anon;
revoke insert, update, delete on seed_stage from authenticated;
create policy seed_stage_admin_read on seed_stage for select to authenticated using (is_admin());
`

writeFileSync(join(root, 'supabase', 'migrations', '0008_seed_picks.sql'), sql)
console.log('Wrote supabase/migrations/0008_seed_picks.sql')
