// IATA airport-code → full name lookup, used to reveal an airport's name when a
// spotter taps a bare code on a card or in the scrapbook. Routes are stored as
// IATA codes only (see lib/route.ts), so this is the display-side mapping.
//
// Not exhaustive — covers the major hubs that scheduled airliners actually fly,
// weighted towards the UK/Europe where most early spotting happens. Unknown
// codes fall back to the bare code (airportName returns null).
const AIRPORTS: Record<string, string> = {
  // United Kingdom & Ireland
  LHR: "London Heathrow",
  LGW: "London Gatwick",
  STN: "London Stansted",
  LTN: "London Luton",
  LCY: "London City",
  SEN: "London Southend",
  MAN: "Manchester",
  BHX: "Birmingham",
  EDI: "Edinburgh",
  GLA: "Glasgow",
  BRS: "Bristol",
  NCL: "Newcastle",
  LPL: "Liverpool",
  LBA: "Leeds Bradford",
  EMA: "East Midlands",
  BFS: "Belfast International",
  BHD: "Belfast City",
  ABZ: "Aberdeen",
  SOU: "Southampton",
  CWL: "Cardiff",
  EXT: "Exeter",
  NWI: "Norwich",
  DUB: "Dublin",
  ORK: "Cork",
  SNN: "Shannon",
  // Western Europe
  CDG: "Paris Charles de Gaulle",
  ORY: "Paris Orly",
  BVA: "Paris Beauvais",
  AMS: "Amsterdam Schiphol",
  FRA: "Frankfurt",
  MUC: "Munich",
  BER: "Berlin Brandenburg",
  DUS: "Düsseldorf",
  HAM: "Hamburg",
  CGN: "Cologne Bonn",
  STR: "Stuttgart",
  BRU: "Brussels",
  CRL: "Brussels Charleroi",
  LUX: "Luxembourg",
  GVA: "Geneva",
  ZRH: "Zurich",
  BSL: "Basel Mulhouse",
  VIE: "Vienna",
  MAD: "Madrid Barajas",
  BCN: "Barcelona El Prat",
  AGP: "Málaga",
  PMI: "Palma de Mallorca",
  ALC: "Alicante",
  VLC: "Valencia",
  SVQ: "Seville",
  IBZ: "Ibiza",
  LIS: "Lisbon",
  OPO: "Porto",
  FAO: "Faro",
  FCO: "Rome Fiumicino",
  CIA: "Rome Ciampino",
  MXP: "Milan Malpensa",
  LIN: "Milan Linate",
  BGY: "Milan Bergamo",
  VCE: "Venice Marco Polo",
  NAP: "Naples",
  BLQ: "Bologna",
  PSA: "Pisa",
  CTA: "Catania",
  NCE: "Nice Côte d'Azur",
  LYS: "Lyon",
  MRS: "Marseille",
  TLS: "Toulouse",
  BOD: "Bordeaux",
  NTE: "Nantes",
  // Nordics & Baltics
  CPH: "Copenhagen",
  ARN: "Stockholm Arlanda",
  OSL: "Oslo Gardermoen",
  HEL: "Helsinki Vantaa",
  KEF: "Reykjavík Keflavík",
  RIX: "Riga",
  TLL: "Tallinn",
  VNO: "Vilnius",
  // Central & Eastern Europe
  WAW: "Warsaw Chopin",
  KRK: "Kraków",
  GDN: "Gdańsk",
  PRG: "Prague",
  BUD: "Budapest",
  OTP: "Bucharest Otopeni",
  SOF: "Sofia",
  BEG: "Belgrade",
  ZAG: "Zagreb",
  LJU: "Ljubljana",
  // Southern Europe & Mediterranean
  ATH: "Athens",
  SKG: "Thessaloniki",
  HER: "Heraklion",
  RHO: "Rhodes",
  JMK: "Mykonos",
  JTR: "Santorini",
  MLA: "Malta",
  LCA: "Larnaca",
  IST: "Istanbul",
  SAW: "Istanbul Sabiha Gökçen",
  AYT: "Antalya",
  // Middle East
  DXB: "Dubai International",
  DWC: "Dubai World Central",
  AUH: "Abu Dhabi",
  DOH: "Doha Hamad",
  BAH: "Bahrain",
  KWI: "Kuwait",
  RUH: "Riyadh",
  JED: "Jeddah",
  TLV: "Tel Aviv Ben Gurion",
  AMM: "Amman Queen Alia",
  CAI: "Cairo",
  // North America
  JFK: "New York JFK",
  EWR: "Newark Liberty",
  LGA: "New York LaGuardia",
  BOS: "Boston Logan",
  IAD: "Washington Dulles",
  DCA: "Washington Reagan",
  PHL: "Philadelphia",
  ATL: "Atlanta",
  MIA: "Miami",
  MCO: "Orlando",
  FLL: "Fort Lauderdale",
  ORD: "Chicago O'Hare",
  MDW: "Chicago Midway",
  DFW: "Dallas Fort Worth",
  IAH: "Houston Bush",
  DEN: "Denver",
  LAS: "Las Vegas Harry Reid",
  LAX: "Los Angeles",
  SFO: "San Francisco",
  SEA: "Seattle Tacoma",
  SAN: "San Diego",
  PHX: "Phoenix Sky Harbor",
  YYZ: "Toronto Pearson",
  YVR: "Vancouver",
  YUL: "Montréal Trudeau",
  YYC: "Calgary",
  MEX: "Mexico City",
  CUN: "Cancún",
  // Asia
  HKG: "Hong Kong",
  PVG: "Shanghai Pudong",
  PEK: "Beijing Capital",
  PKX: "Beijing Daxing",
  CAN: "Guangzhou",
  NRT: "Tokyo Narita",
  HND: "Tokyo Haneda",
  KIX: "Osaka Kansai",
  ICN: "Seoul Incheon",
  TPE: "Taipei Taoyuan",
  SIN: "Singapore Changi",
  KUL: "Kuala Lumpur",
  BKK: "Bangkok Suvarnabhumi",
  DMK: "Bangkok Don Mueang",
  CGK: "Jakarta",
  MNL: "Manila",
  DEL: "Delhi Indira Gandhi",
  BOM: "Mumbai",
  BLR: "Bengaluru",
  MAA: "Chennai",
  HYD: "Hyderabad",
  CMB: "Colombo",
  MLE: "Malé",
  // Africa
  JNB: "Johannesburg",
  CPT: "Cape Town",
  NBO: "Nairobi",
  ADD: "Addis Ababa",
  LOS: "Lagos",
  CMN: "Casablanca",
  RAK: "Marrakesh",
  TUN: "Tunis",
  ALG: "Algiers",
  MRU: "Mauritius",
  // Oceania & South America
  SYD: "Sydney",
  MEL: "Melbourne",
  BNE: "Brisbane",
  PER: "Perth",
  AKL: "Auckland",
  GRU: "São Paulo Guarulhos",
  GIG: "Rio de Janeiro Galeão",
  EZE: "Buenos Aires Ezeiza",
  SCL: "Santiago",
  BOG: "Bogotá",
  LIM: "Lima",
  PTY: "Panama City Tocumen",
};

/** Full airport name for an IATA code, or null if not in the lookup. */
export function airportName(code?: string | null): string | null {
  if (!code) return null;
  return AIRPORTS[code.trim().toUpperCase()] ?? null;
}

/** Sorted {code, name} list — powers the home-airport autocomplete. */
export const AIRPORTS_LIST: { code: string; name: string }[] = Object.entries(AIRPORTS)
  .map(([code, name]) => ({ code, name }))
  .sort((a, b) => a.code.localeCompare(b.code));
