// Analyse the 24h snapshot (scripts/.rarity-state.json) and generate the
// measured re-tier SQL. Prints the distribution so thresholds can be
// sanity-checked before anything is applied; writes scripts/rarity-retier.sql
// for review — nothing touches the database from here.
//
// Tier = f(distinct airframes over Europe in 24h), then the DB applies
// category floors (rarity_floor) so a helicopter can never fall below
// uncommon, military below rare, vintage below epic. Types in the universe
// but ABSENT from the snapshot re-tier to at least 'rare' (never demoting
// an existing higher tier — Spitfires don't fly every day).
//
// Threshold defaults are placeholders until real data is in; run with e.g.
//   node scripts/rarity-apply.mjs --common=400 --uncommon=80 --rare=12 --epic=2
// to recalibrate. A type at/above the value gets that tier; below --epic ⇒ legendary.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const STATE_FILE = join(HERE, ".rarity-state.json");
const OUT_SQL = join(HERE, "rarity-retier.sql");

if (!existsSync(STATE_FILE)) {
  console.error("No snapshot state found — run scripts/rarity-snapshot.mjs first.");
  process.exit(1);
}

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const m = a.match(/^--(\w+)=(\d+)$/);
    return m ? [m[1], Number(m[2])] : [a, true];
  }),
);
const T = { common: args.common ?? 400, uncommon: args.uncommon ?? 80, rare: args.rare ?? 12, epic: args.epic ?? 2 };

const state = JSON.parse(readFileSync(STATE_FILE, "utf8"));
const rounds = state.rounds.length;

const rows = Object.entries(state.types)
  .filter(([code]) => code !== "ZZZZ") // ICAO "type unknown" — not a real type
  .map(([code, t]) => {
    const airframes = t.hexes.length;
    const milPct = airframes ? Math.round((100 * t.military) / airframes) : 0;
    const topCat = Object.entries(t.adsbCats ?? {}).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "";
    const tier =
      airframes >= T.common ? "common"
      : airframes >= T.uncommon ? "uncommon"
      : airframes >= T.rare ? "rare"
      : airframes >= T.epic ? "epic"
      : "legendary";
    return { code, airframes, milPct, topCat, tier };
  })
  .sort((a, b) => b.airframes - a.airframes);

console.log(`Snapshot: ${rounds} rounds since ${state.startedAt}`);
console.log(`Thresholds: common>=${T.common} uncommon>=${T.uncommon} rare>=${T.rare} epic>=${T.epic} else legendary\n`);
console.log("code  airframes/24h  tier        mil%  adsb-cat");
for (const r of rows.slice(0, 80)) {
  console.log(
    `${r.code.padEnd(5)} ${String(r.airframes).padStart(12)}  ${r.tier.padEnd(10)} ${String(r.milPct).padStart(4)}  ${r.topCat}`,
  );
}
if (rows.length > 80) console.log(`… and ${rows.length - 80} more types`);

const byTier = {};
for (const r of rows) byTier[r.tier] = (byTier[r.tier] ?? 0) + 1;
console.log("\nTier counts across observed types:", byTier);

// ---- SQL: measured tiers (floors applied DB-side), absent types >= rare ----
const values = rows.map((r) => `('${r.code.replace(/'/g, "")}','${r.tier}')`).join(",\n  ");
const sql = `-- Generated by scripts/rarity-apply.mjs — ${new Date().toISOString()}
-- Snapshot: ${rounds} rounds from ${state.startedAt}; thresholds ${JSON.stringify(T)}
-- Review, then apply as a migration (measured tiers, category floors, absent-type
-- promotion, the measured_rarity seed, and the per-sighting rarity backfill).
-- Requires the measured_rarity table + register_aircraft_type v2 (migration
-- measured_rarity_lookup).

update public.aircraft_types at
set rarity = case
  when rarity_rank(v.tier) < rarity_rank(rarity_floor(at.category))
    then rarity_floor(at.category)
  else v.tier
end
from (values
  ${values}
) as v(code, tier)
where at.code = v.code;

-- Seed/refresh the measured-tier lookup: register_aircraft_type() consults it
-- so a type's FIRST capture lands on the measured tier (not the 'rare' default)
-- without pre-inserting hundreds of placeholder rows into the Type Book.
insert into public.measured_rarity (code, tier)
values
  ${values}
on conflict (code) do update set tier = excluded.tier;

-- Universe types never seen airborne in the snapshot: at least 'rare'
-- (keep existing higher tiers — curated legendaries stay legendary).
update public.aircraft_types
set rarity = case
  when rarity_rank(rarity_floor(category)) > rarity_rank('rare') then rarity_floor(category)
  else 'rare'
end
where code not in (${rows.map((r) => `'${r.code.replace(/'/g, "")}'`).join(",")})
  and rarity_rank(rarity) < rarity_rank('rare');

-- Curated pins (rarity_overrides) always win over measurement — applied last
-- so re-running the snapshot→apply cycle never clobbers them.
update public.aircraft_types at
set rarity = o.tier
from public.rarity_overrides o
where at.code = o.code and at.rarity is distinct from o.tier;

-- Denormalised per-sighting rarity follows the universe.
update public.sightings s
set rarity = at.rarity
from public.aircraft_types at
where at.code = s.aircraft_type and s.rarity is distinct from at.rarity;
`;

writeFileSync(OUT_SQL, sql);
console.log(`\nSQL written to ${OUT_SQL} — review before applying.`);
